kind: ModelTraining
id: wine
spec:
  model:
    name: wine
    version: 1.0
  toolchain: mlflow
  entrypoint: main
  workDir: mlflow/sklearn/wine
  data:
    - connName: wine
      localPath: mlflow/sklearn/wine/wine-quality.csv
  hyperParameters:
    alpha: "1.0"
  resources:
    limits:
      cpu: 2024m
      memory: 2024Mi
    requests:
      cpu: 1024m
      memory: 1024Mi
  vcsName: legion-examples
  
